# Generated by Django 2.0.6 on 2018-06-11 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20180611_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='author',
        ),
        migrations.AlterField(
            model_name='student',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.School'),
        ),
    ]
